# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kirigami': '@stable'
    'libraries/kpublictransport': "@latest"

- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/qqc2-desktop-style': '@stable'

Options:
  require-passing-tests-on: [ '@all' ]
