# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'Android', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kcontacts': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'libraries/kpublictransport': "@latest-kf6"
    'libraries/kirigami-addons': 'v1.11.0'

- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'

Options:
  require-passing-tests-on: [ '@all' ]
